#!/usr/bin/env bash
# Use bubblewrap to run /bin/sh reusing the host OS binaries (/usr), but with
# separate /tmp, /home, /var, /run, and /etc. For /etc we just inherit the
# host's resolv.conf, and set up "stub" passwd/group files.  Not sharing
# /home for example is intentional.  If you wanted to, you could design
# a bwrap-using program that shared individual parts of /home, perhaps
# public content.
#
# Another way to build on this example is to remove --share-net to disable
# networking.
set -euo pipefail

set -x

CONFIG="$HOME/.config/mpv/mpv.conf"
XAUTH="$HOME/.Xauthority"

declare -a EXTRA_ARGS

# Networking
EXTRA_ARGS+=(--ro-bind /etc/resolv.conf /etc/resolv.conf)
EXTRA_ARGS+=(--ro-bind /etc/ssl /etc/ssl)
EXTRA_ARGS+=(--ro-bind /etc/ca-certificates /etc/ca-certificates)

# Video acceleration
if [ -c /dev/dri/renderD128 ]; then
  echo TODO
  # TODO: This currently errors: "drmGetMagic" failed
  #EXTRA_ARGS+=(--dev-bind /dev/dri/renderD128 /dev/dri/renderD128)
  #EXTRA_ARGS+=(--dev-bind /dev/dri/card1 /dev/dri/card1)
fi

if [ "${WAYLAND_DISPLAY:-}" != "" ]; then
  EXTRA_ARGS+=(--setenv WAYLAND_DISPLAY "$WAYLAND_DISPLAY")
  EXTRA_ARGS+=(--ro-bind "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY")
# X11
elif [ "${DISPLAY:-}" != "" ]; then
  EXTRA_ARGS+=(--setenv DISPLAY "$DISPLAY")
  EXTRA_ARGS+=(--ro-bind "$XAUTH" "$XAUTH")
  EXTRA_ARGS+=(--ro-bind /tmp/.X11-unix/X0 /tmp/.X11-unix/X0)
fi

if [ -f "$CONFIG" ]; then
  EXTRA_ARGS+=(--ro-bind "$CONFIG" "$CONFIG")
fi

# TODO: Don't bind entire of /usr

# SECCOMP
SECCOMP=""

if [ "$SECCOMP" != "" ]; then
  EXTRA_ARGS+=(--seccomp 13)
fi

# Run
(exec bwrap \
      --ro-bind /usr /usr \
      --dir /tmp \
      --dir /var \
      --symlink ../tmp var/tmp \
      --proc /proc \
      --dev /dev \
      --tmpfs "$HOME" \
      --ro-bind /etc/fonts /etc/fonts \
      --ro-bind /usr/share/fontconfig /usr/share/fontconfig \
      --symlink usr/lib /lib \
      --symlink usr/lib64 /lib64 \
      --symlink usr/bin /bin \
      --symlink usr/sbin /sbin \
      --dir "$XDG_RUNTIME_DIR" \
      --ro-bind-try "$XDG_RUNTIME_DIR/pulse" "$XDG_RUNTIME_DIR/pulse" \
      --unshare-user \
      --disable-userns \
      --assert-userns-disabled \
      --unshare-pid \
      --unshare-cgroup-try \
      --unshare-uts \
      --hostname localhost \
      --die-with-parent \
      --dir /run/user/$(id -u) \
      --clearenv \
      ${EXTRA_ARGS[@]} \
      --setenv XDG_RUNTIME_DIR "/run/user/$(id -u)" \
      --setenv PS1 "bwrap-mpv$ " \
      --setenv PATH "/bin:/usr/bin" \
      --file 11 /etc/passwd \
      --file 12 /etc/group \
      mpv $@) \
    11< <(getent passwd $UID 65534) \
    12< <(getent group $(id -g) 65534) \
    13< <(printf "%s" "$SECCOMP" | base64 -d)

